### ISSUE TITLE
No named parameter with the name 'clipBehavior'

### ISSUE THREAD

**Issue by shw2ypro** [yako-dev/flutter_badges#32]
Good Night
After upgrading to   badges: ^1.1.3
I got this error
what should i do ???

`Compiler message:
/C:/flutter/.pub-cache/hosted/pub.dartlang.org/badges-1.1.3/lib/src/badge.dart:83:9: Error: No named parameter with the name 'clipBehavior'.
        clipBehavior: Clip.none,
        ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/widgets/basic.dart:3210:3: Context: Found this candidate, but the arguments don't match.
  Stack({
  ^^^^^`

**Comment by culunvb** [comment]
I found the same issues

**Comment by ahmedGibran** [comment]
I found the same issues ???

**Comment by ahmedGibran** [comment]
@culunvb @shw2ypro any solution?

**Comment by moga111** [comment]
It looks like the changes made to this library were ahead of the stable release. Make sure to update flutter to latest version on the stable channel.

Its resolved now.

**Comment by shw2ypro** [comment]
@ahmedGibran 
i downgrade version to 1.1.1 and it worked fine
Hint: if u downgraded version and still show the same error just edit dart tool file and change package version from 1.1.3 to 1.1.1

**Comment by RusKryzhanovskiy** [comment]
@shw2ypro, you can use 1.1.4
